Zur Visualisierung der Daten stellt die VR-Anwendung vier Komponenten zur Verfügung, 
welche hierachisch aufgebaut sind. Die _Visualizer_-Komponente stellt die Schnittstelle
zwischen der UI und der internen Datenstruktur dar. Sie ist dafür zuständig, die Daten 
aus einer CSV-Datei einzulesen, der UI die nötigen Informationen bereitzustellen und 
die vom Benutzer gewählte _ScatterplotMatrix_ zu erstellen. Die _ScatterplotMatrix_-Komponente
wird als Kind des _Visualizers_ erstellt. Sie ist für das Erzeugen und Positionieren der
einzelnen _Scatterplots_ verantwortlich. Die _Scatterplot_-Komponente erstellt ein 3D-Diagramm,
in dem die drei übergebenen Dimensionen für alle _DataPoints_ gegeneinander aufgetragen werden.
Die _DataPoint_-Komponente stellt einen Datenpunkt als Kugel im _Scatterplot_ dar. Wie die Szene
nach dem Importieren einer CSV-Datei aussieht, ist auf <<scene>> gezeigt. Im Folgenden
werden die Komponenten genauer beschrieben.

[[scene, Abb. {counter:figure-counter}]]
[ditaa]
.Szene
....
+----------+
|Visualizer|
+----------+
        |   +-----------------+
        +-->|ScatterplotMatrix|
            +-----------------+
                        |   +-----------+
                        +-->|Scatterplot|
                        :   +-----------+
                        |           |   +---------+
                        |           +-->|DataPoint|
                        |           |   +---------+
                        |           |
                        |           |   +---------+
                        |           +-->|DataPoint|
                        |           :   +---------+
                        |           |
                        |           |   +---------+
                        |           +-->|DataPoint|
                        |               +---------+
                        |   +-----------+
                        +-->|Scatterplot|
                            +-----------+
                                    |   +---------+
                                    +-->|DataPoint|
                                    |   +---------+
                                    |
                                    |   +---------+
                                    +-->|DataPoint|
                                    :   +---------+
                                    |
                                    |   +---------+
                                    +-->|DataPoint|
                                        +---------+
....

=== Visualizer
Die Schnittstelle des _Visualizer_ besteht drei Methoden und einem Attribut. Die Methoden
_LoadDataSource(TextAsset)_ wird vom _ImportDialog_ aufgerufen, wenn der Benutzer im DropDown-Menü
eine neue CSV-Datei auswählt. Neben dem eigentlichen Laden der CSV-Datei werden zusätzlich alle
möglichen 3er-Kombinationen der in der Datei enthaltenen Dimensionen gebildet. Hierzu wird 
_CalculatePossibleScatterplots()_ aufgerufen, welche ein zweidimensionales _int_-Array
zurück gibt. Die erste Dimension dieses Arrays stellt dabei die einzelnen Kombinationen der 
Dimensionen der CSV-Datei dar. Die zweite Dimension hat die Größe 3 und besteht aus den drei Indizes
der jeweiligen Dimension der CSV-Datei. Der _ImportDialog_ erhält die 3er-Kombinationen als _string_
-Array über die Methode _GetPossibleScatterplots()_. Somit können dem Benutzer die möglichen
_Scatterplot_-Varianten angezeigt werden. Wird der _Importieren_-Button angeklickt, ruft der _ImportDialog_
die Methode _CreateScatterplotMatrix(int[])_ auf. Über den Parameter werden die Indizes der vom Benutzer
gewünschten _Scatterplots_ übergeben. Es wird dann eine neue _ScatterplotMatrix_ instantiiert. Wurder
vorher bereits eine _ScatterplotMatrix_ erzeugt, wird diese gelöscht. Es ist somit zu jeder Zeit immer
nur eine _ScatterplotMatrix_ in der Szene. Über das Attribut _pointSize_ kann die Größe der _DataPoints_
angepasst werden. Der _ImportDialog_ inkrementiert bzw. dekrementiert diesen Wert, wenn der Benutzer die
entsprechenden Buttons klickt.

=== Programmablauf
Das folgende Diagramm stellt den Programmablauf beim erstmaligen Starten der Anwendung dar:

* Blub
** Blub
* blub

Blub

. Ich
.. Mag 
... Züge
. du
.. magst
... LKW
.... Tut Tut


==== Neue Subüberschrift
Blub <<referenz_auf_bereich>>

[[referenz_auf_bereich]]
.Mein Bereich
====
Übernimmt Ascii Zeug
====

[source, c#]
.Source Code
----
public void Foo(){

}
----

Und noch Ref auf Überschrift <<Neue Subüberschrift>>.