= Dokumentation VR-Visualization: Virtual Reality, Master Informatik
:author: Matthias Haselmaier, Andreas M. Brunnet
:vr: Virtual Reality
:icons: font
:imagesdir: imgs/
:figure-caption: Abbildung
:listing-caption: Listing
:example-caption: Beispiel
:table-caption: Tabelle
:source-highlighter: pygments
:figure-counter: 0

== Vorwort
Im Rahmen der Veranstaltung _{vr}_ wurde eine VR-Anwendung auf Basis der Unity 3D-Engine entwickelt, mit deren Hilfe eine Betrachung von Machine Learning Daten im Raum ermöglicht wird. Hierbei hat der Anwender die Möglichkeit innerhalb der als Scatterplots visualisierten Daten umher zu wandern. Darüber hinaus lässt sich ein für den Nutzer interessanter Datenpunkt mittels VR üblicher Selektiergestik auswählen. 
Die Attribute und Werte des selektierten Datenpunks werden relativ zu seiner Position dem Nutzer dargestellt. Über das Hervorheben des selektierten Punktes in sämtlichen Scatterplot-Matrizen hat der Anwender direkte Übersicht über die Verteilung des Punktes innerhalb des Datensets.

== Allgemeine Informationen
include::about_vrvis.adoc[]

== Architektur der Anwendung
include::architecture_desc.adoc[]

[bibliography]
== Quellen / Ressourcen
- [[[MiddleVR, mvr]]]: https://www.middlevr.com/home
- [[[IATK, iatk]]] Immersive Analytics Toolkit: https://github.com/MaximeCordeil/IATK
- [[[VRTK, vrtk]]] Virtual Reality Toolkit: https://vrtoolkit.readme.io
- [[[SteamVR, svr]]]: https://steamcommunity.com/steamvr
- [[[GitHub-Repository, github]]] Projekt Repository: https://github.com/MHaselmaier/VR-Visualization.git
- [[[Unity-Documentation, udoc]]]: https://docs.unity3d.com/Manual/index.html
- [[[MiddleVR-Documentation, mdoc]]]: https://www.middlevr.com/doc/current/