= Technische Dokumentation VR-Visualization: Virtual Reality, Master Informatik
include::header.adoc[]

== Vorwort
Im Rahmen der Veranstaltung _{vr}_ wurde eine VR-Anwendung auf Basis der Unity 3D-Engine entwickelt, mit deren Hilfe eine Betrachung von Machine Learning Daten im Raum ermöglicht wird. Hierbei hat der Anwender die Möglichkeit innerhalb der als Scatterplots visualisierten Daten umher zu wandern. Darüber hinaus lässt sich ein für den Nutzer interessanter Datenpunkt mittels VR üblicher Selektiergestik auswählen.
Die Attribute und Werte des selektierten Datenpunks werden relativ zu seiner Position dem Nutzer dargestellt. Über das Hervorheben des selektierten Punktes in sämtlichen Scatterplot-Matrizen hat der Anwender direkte Übersicht über die Verteilung des Punktes innerhalb des Datensets.

== Software und Bibliotheken
=== Verwendete Software und Bibliotheken
*MiddleVR* (<<MiddleVR>>): Dient der Entkopplung von VR-Hardware und der Applikation. Als Middleware abstrahiert MiddleVR Eingaben durch Hardware wie der HTC Vive Pro und stellt diese auf Seite der Anwendung als verallgemeinerte Schnittstelle zur Verfügung.

[NOTE]
Während der Navigation in UI Komponenten fiel auf, dass Tasteneingaben nicht _debounced_ werden. So werden beispielsweise Checkboxen schwer steuerbar. Auch andere UI Komponenten waren unter diesen Bedingungen nicht zufiedenstellend nutzbar.
Entsprechend wurde innerhalb der zuständigen MiddleVR Klasse _VRCanvas_ die Abfrage von Tastenevents auf _Toogled_ umgestellt, um so ein _pressed_ / _released_ Verhalten zu erhalten.

*IATK* (<<IATK>>): Das Toolkit stellt eine Reihe von Funktionalitäten für das Arbeiten mit Daten zur Verfügung. Unter anderem ist ein CSV-Parser enthalten, der im Gegensatz zu einem üblichen CSV-Parser Wertnormalisierungen unabhängig vom vorliegenden Datentyp vornimmt. 

[NOTE]
Es musste eine Anpassung am Parser vorgenommen werden. Dort wird in der Methode _GetOriginalValue_ ein Float-Wert als Index für ein Array genommen. Hierbei wird die implizite Typkonvertierung und die daraus resultierende Abrundung zum Problem, da an diesem Punkt ein Runden zur nächsten Ganzzahl erfolgen sollte. Dieser Fehler wurde mittels _Mathf.Round_ behoben.

Die Möglichkeiten des Frameworks zur Datenvisualisierung wurden nach ersten Tests mit dem Framework verworfen, da eine Eigenimplementierung der nötigen Visualisierungskomponenten mit den nötigen Interaktionsmöglichkeiten, wie der Datenpunktauswahl (siehe <<Kurzeinleitung>>, <<datapoint_selection>>) somit umsetzbar wurde. 

=== Verworfene Software und Bibliotheken
*VRTK* (<<VRTK>>): Wie auch MiddleVR dient VRTK der Entkopplung von Eingabegeräten und der Applikation. Eine erste Integration in das Projekt verlief ohne größere Probleme, sodass das Testen der Anwendung mittels Maus und Tastatur (Modus: Simulation) möglich war. 
Probleme traten jedoch beim Versuch der Integration einer Vive-Pro Konfiguration auf, da VRTK seit einiger Zeit nicht mehr aktualisiert wird. Entsprechend kam es zu Komplikationen mit der aktuellen API der Vive-Pro (SteamVR, <<SteamVR>>). 
Entsprechend wurde als alternative Lösung MiddleVR erfolgreich evaluiert und im Projekt statt VRTK integriert.

== Architektur der Anwendung

Zur Visualisierung der Daten stellt die VR-Anwendung vier Komponenten zur Verfügung, 
welche hierachisch aufgebaut sind. Die _Visualizer_-Komponente stellt die Schnittstelle
zwischen der UI und der internen Datenstruktur dar. Sie ist dafür zuständig, die Daten 
aus einer CSV-Datei einzulesen, der UI die nötigen Informationen bereitzustellen und 
die vom Benutzer gewählte _ScatterplotMatrix_ zu erstellen. Die _ScatterplotMatrix_-Komponente
wird als Kind des _Visualizers_ erstellt. Sie ist für das Erzeugen und Positionieren der
einzelnen _Scatterplots_ verantwortlich. Die _Scatterplot_-Komponente erstellt ein 3D-Diagramm,
in dem die drei übergebenen Dimensionen für alle _DataPoints_ gegeneinander aufgetragen werden.
Die _DataPoint_-Komponente stellt einen Datenpunkt als Kugel im _Scatterplot_ dar. Wie die Szene
nach dem Importieren einer CSV-Datei aussieht, ist auf <<scene>> gezeigt. Im Folgenden
werden die Komponenten genauer beschrieben.

[[scene, Abb. {counter:figure-counter}]]
[ditaa]
.Szene
....
+----------+
|Visualizer|
+----------+
        |   +-----------------+
        +-->|ScatterplotMatrix|
            +-----------------+
                        |   +-----------+
                        +-->|Scatterplot|
                        :   +-----------+
                        |           |   +---------+
                        |           +-->|DataPoint|
                        |           |   +---------+
                        |           |
                        |           |   +---------+
                        |           +-->|DataPoint|
                        |           :   +---------+
                        |           |
                        |           |   +---------+
                        |           +-->|DataPoint|
                        |               +---------+
                        |   +-----------+
                        +-->|Scatterplot|
                            +-----------+
                                    |   +---------+
                                    +-->|DataPoint|
                                    |   +---------+
                                    |
                                    |   +---------+
                                    +-->|DataPoint|
                                    :   +---------+
                                    |
                                    |   +---------+
                                    +-->|DataPoint|
                                        +---------+
....

=== Visualizer
Die Schnittstelle des _Visualizer_ besteht drei Methoden und einem Attribut. Die Methoden
_LoadDataSource(TextAsset)_ wird vom _ImportDialog_ aufgerufen, wenn der Benutzer im DropDown-Menü
eine neue CSV-Datei auswählt. Neben dem eigentlichen Laden der CSV-Datei werden zusätzlich alle
möglichen 3er-Kombinationen der in der Datei enthaltenen Dimensionen gebildet. Hierzu wird 
_CalculatePossibleScatterplots()_ aufgerufen, welche ein zweidimensionales _int_-Array
zurück gibt. Die erste Dimension dieses Arrays stellt dabei die einzelnen Kombinationen der 
Dimensionen der CSV-Datei dar. Die zweite Dimension hat die Größe 3 und besteht aus den drei Indizes
der jeweiligen Dimension der CSV-Datei. Der _ImportDialog_ erhält die 3er-Kombinationen als _string_
-Array über die Methode _GetPossibleScatterplots()_. Somit können dem Benutzer die möglichen
_Scatterplot_-Varianten angezeigt werden. Wird der _Importieren_-Button angeklickt, ruft der _ImportDialog_
die Methode _CreateScatterplotMatrix(int[])_ auf. Über den Parameter werden die Indizes der vom Benutzer
gewünschten _Scatterplots_ übergeben. Es wird dann eine neue _ScatterplotMatrix_ instantiiert. Wurder
vorher bereits eine _ScatterplotMatrix_ erzeugt, wird diese gelöscht. Es ist somit zu jeder Zeit immer
nur eine _ScatterplotMatrix_ in der Szene. Über das Attribut _pointSize_ kann die Größe der _DataPoints_
angepasst werden. Der _ImportDialog_ inkrementiert bzw. dekrementiert diesen Wert, wenn der Benutzer die
entsprechenden Buttons klickt.

=== Programmablauf
Das folgende Diagramm stellt den Programmablauf beim erstmaligen Starten der Anwendung dar:

* Blub
** Blub
* blub

Blub

. Ich
.. Mag 
... Züge
. du
.. magst
... LKW
.... Tut Tut


==== Neue Subüberschrift
Blub <<referenz_auf_bereich>>

[[referenz_auf_bereich]]
.Mein Bereich
====
Übernimmt Ascii Zeug
====

[source, c#]
.Source Code
----
public void Foo(){

}
----

Und noch Ref auf Überschrift <<Neue Subüberschrift>>.

include::bib.adoc[]