= Technische Dokumentation VR-Visualization: Virtual Reality, Master Informatik
:author: Matthias Haselmaier, Andreas M. Brunnet
:vr: Virtual Reality
:icons: font
:imagesdir: imgs/
:figure-caption: Abbildung
:listing-caption: Listing
:example-caption: Beispiel
:table-caption: Tabelle
:source-highlighter: pygments
:figure-counter: 0

== Vorwort
Im Rahmen der Veranstaltung _{vr}_ wurde eine VR-Anwendung auf Basis der Unity 3D-Engine entwickelt, mit deren Hilfe eine Betrachung von Machine Learning Daten im Raum ermöglicht wird. Hierbei hat der Anwender die Möglichkeit innerhalb der als Scatterplots visualisierten Daten umher zu wandern. Darüber hinaus lässt sich ein für den Nutzer interessanter Datenpunkt mittels VR üblicher Selektiergestik auswählen. 
Die Attribute und Werte des selektierten Datenpunks werden relativ zu seiner Position dem Nutzer dargestellt. Über das Hervorheben des selektierten Punktes in sämtlichen Scatterplot-Matrizen hat der Anwender direkte Übersicht über die Verteilung des Punktes innerhalb des Datensets.

== Software und Bibliotheken
=== Verwendete Software und Bibliotheken
*MiddleVR* (<<MiddleVR>>): Dient der Entkopplung von VR-Hardware und der Applikation. Als Middleware abstrahiert MiddleVR Eingaben durch Hardware wie der HTC Vive Pro und stellt diese auf Seite der Anwendung als verallgemeinerte Schnittstelle zur Verfügung.

[NOTE]
Während der Navigation in UI Komponenten fiel auf, dass Tasteneingaben nicht _debounced_ werden. So werden beispielsweise Checkboxen schwer steuerbar. Auch andere UI Komponenten waren unter diesen Bedingungen nicht zufriedenstellend nutzbar.
Entsprechend wurde innerhalb der zuständigen MiddleVR Klasse _VRCanvas_ die Abfrage von Tastenevents auf _Toogled_ umgestellt, um so ein _pressed_ / _released_ Verhalten zu erhalten.

*IATK* (<<IATK>>): Das Toolkit stellt eine Reihe von Funktionalitäten für das Visualisieren von Daten zur Verfügung. Unter anderem ist ein CSV-Parser enthalten, der im Gegensatz zu einem üblichen CSV-Parser Wertnormalisierungen unabhängig vom vorliegenden Datentyp vornimmt. 

[NOTE]
Es musste eine Anpassung am Parser vorgenommen werden. Dort wird in der Methode _GetOriginalValue_ der normalisiert Wert auf seinen originalen originalen Wertebereich gebracht.
Hierbei kann es zu Rundungsfehlern kommen, zum Beispiel 0,9999 statt den erwarteten 1,0. Ist der gesuchte Wert vom Typ _string_, wird der resultierende Wert als Index in einem 
Array verwendet. Hierfür wird der _float_ Wert in einen _int_ gecastet. Die führte dazu, dass der falsche originale _string_-Wert zurückgegeben wurde. Zur Lösung wurde der resultierende
Wert zuerst mit _Mathf.round()_ gerundet, bevor es in einen _int_ gecastet wird.

Die Möglichkeiten des Frameworks zur Datenvisualisierung wurden nach ersten Tests mit dem Framework aufgrund von schlechter Dokumentation verworfen. Es wurde eine Eigenimplementierung der nötigen Visualisierungskomponenten mit den nötigen Interaktionsmöglichkeiten, wie der Datenpunktauswahl (siehe <<Kurzeinleitung>>, <<datapoint_selection>>) umgesetzt. 

=== Verworfene Software und Bibliotheken
*VRTK* (<<VRTK>>): Wie auch MiddleVR dient VRTK der Entkopplung von Eingabegeräten und der Applikation. Eine erste Integration in das Projekt verlief ohne größere Probleme, sodass das Testen der Anwendung mittels Maus und Tastatur (Modus: Simulation) möglich war. 
Probleme traten jedoch beim Versuch der Integration einer Vive-Pro Konfiguration auf, da VRTK seit einiger Zeit nicht mehr aktualisiert wird. Entsprechend kam es zu Komplikationen mit der aktuellen API der Vive-Pro (SteamVR, <<SteamVR>>). 
Entsprechend wurde als alternative Lösung MiddleVR erfolgreich evaluiert und im Projekt statt VRTK integriert.


== Architektur der Anwendung

Zur Visualisierung der Daten stellt die VR-Anwendung vier Komponenten zur Verfügung, 
welche hierachisch aufgebaut sind. Die _Visualizer_-Komponente stellt die Schnittstelle
zwischen der UI und der internen Datenstruktur dar. Sie ist dafür zuständig, die Daten 
aus einer CSV-Datei einzulesen, der UI die nötigen Informationen bereitzustellen und 
die vom Benutzer gewählte _ScatterplotMatrix_ zu erstellen. Die _ScatterplotMatrix_-Komponente
wird als Kind des _Visualizers_ erstellt. Sie ist für das Erzeugen und Positionieren der
einzelnen _Scatterplots_ verantwortlich. Die _Scatterplot_-Komponente erstellt ein 3D-Diagramm,
in dem die drei übergebenen Dimensionen für alle _DataPoints_ gegeneinander aufgetragen werden.
Die _DataPoint_-Komponente stellt einen Datenpunkt als Kugel im _Scatterplot_ dar. Wie die Szene
nach dem Importieren einer CSV-Datei aussieht, ist auf <<scene>> gezeigt. Im Folgenden
werden die Komponenten genauer beschrieben.

[[scene, Abb. {counter:figure-counter}]]
[ditaa]
.Szene
....
+----------+
|Visualizer|
+----------+
        |   +-----------------+
        +-->|ScatterplotMatrix|
            +-----------------+
                        |   +-----------+
                        +-->|Scatterplot|
                        :   +-----------+
                        |           |   +---------+
                        |           +-->|DataPoint|
                        |           |   +---------+
                        |           |
                        |           |   +---------+
                        |           +-->|DataPoint|
                        |           :   +---------+
                        |           |
                        |           |   +---------+
                        |           +-->|DataPoint|
                        |               +---------+
                        |   +-----------+
                        +-->|Scatterplot|
                            +-----------+
                                    |   +---------+
                                    +-->|DataPoint|
                                    |   +---------+
                                    |
                                    |   +---------+
                                    +-->|DataPoint|
                                    :   +---------+
                                    |
                                    |   +---------+
                                    +-->|DataPoint|
                                        +---------+
....

=== Visualizer
Die Schnittstelle des _Visualizer_ besteht drei Methoden und einem Attribut. Die Methoden
_LoadDataSource(TextAsset)_ wird vom _ImportDialog_ aufgerufen, wenn der Benutzer im DropDown-Menü
eine neue CSV-Datei auswählt. Neben dem eigentlichen Laden der CSV-Datei werden zusätzlich alle
möglichen 3er-Kombinationen der in der Datei enthaltenen Dimensionen gebildet. Hierzu wird 
_CalculatePossibleScatterplots()_ aufgerufen, welche ein zweidimensionales _int_-Array
zurück gibt. Die erste Dimension dieses Arrays stellt dabei die einzelnen Kombinationen der 
Dimensionen der CSV-Datei dar. Die zweite Dimension hat die Größe 3 und besteht aus den drei Indizes
der jeweiligen Dimension der CSV-Datei. Der _ImportDialog_ erhält die 3er-Kombinationen als _string_
-Array über die Methode _GetPossibleScatterplots()_. Somit können dem Benutzer die möglichen
_Scatterplot_-Varianten angezeigt werden. Wird der _Importieren_-Button angeklickt, ruft der _ImportDialog_
die Methode _CreateScatterplotMatrix(int[])_ auf. Über den Parameter werden die Indizes der vom Benutzer
gewünschten _Scatterplots_ übergeben. Es wird dann eine neue _ScatterplotMatrix_ instantiiert. Wurder
vorher bereits eine _ScatterplotMatrix_ erzeugt, wird diese gelöscht. Es ist somit zu jeder Zeit immer
nur eine _ScatterplotMatrix_ in der Szene. Über das Attribut _pointSize_ kann die Größe der _DataPoints_
angepasst werden. Der _ImportDialog_ inkrementiert bzw. dekrementiert diesen Wert, wenn der Benutzer die
entsprechenden Buttons klickt.

=== ScatterplotMatrix
Die _ScatterplotMatrix_ kapselt und erzeugt _Scatterplots_. Nachdem eine _ScatterplotMatrix_ erzeugt
wurde sollte immer die Methode _Initialize(CSVDataSource, int[,], float)_ aufgerufen werden. Durch 
den Aufruf dieser Methode wird die Referenz auf die eingelesene CSV-Datei gesetzt, die gewünschten
Scatterplots angegeben und die initiale Größe der _DataPoints_ definiert. In ihr wir die private
Methode _CreateScatterplots(CSVDataSource, int[,])_ aufgerufen. Hierdurch werden die angegebenen
_Scatterplots_ erzeugt. Zum Erzeugen der Scatterplots wird die Coroutine _CreateScatterplotsCoroutine(GameObjec, CSVDataSource, int[,], int)_
verwendet. Mit dem Frame wird ein _Scatterplot_ erzeugt. Diese Variante wurde gewählt, damit die
Anwendung während dem Erzeugen der _Scatterplots_ nicht einfriert. Die letzte Method der Komponente
_ScatterplotMatrix_ ist _SelectDataPoint(int)_. Sie wird von einem _DataPoint_ mit seinem Index aufgerufen,
wenn er vom Benutzer ausgewählt wird. Aus der _ScatterplotMatrix_ wird der Index des jeweiligen _DataPoints_
an alle _Scatterplots_ weitergegeben. Somit benachrichtigt ein ausgewählter _DataPoint_ über die _ScatterplotMatrix_
alle _Scatterplots_ und diese können den _DataPoint_ mit dem gegebenen Index hervorheben.

=== Scatterplot
Einem _Scatterplot_ sind immer drei Spalten der CSV-Datei zugeordnet, welche über die Attribute _xDim_,
_yDim_ und _zDim_ bestimmt sind. Wie auch schon bei der _ScatterplotMatrix_ sollte nach dem Erzeugen
eines _Scatterplot_ immer die Methode _Initialize(CSVDataSource, float, float, float, int, int ,int)_
aufgerufen werden. Hierbei bestimmen die ersten beiden _float_-Werte die Position des _Scatterplots_ 
in der Ebene, der letzte _float_-Wert bestimmt die initiale _DataPoint_ Größe. Die letzten drei _int_-Werte
definieren die drei bereits angesprochenen Spalten der CSV-Datei. Durch den Aufruf von _Initialize(..)_ 
werden außerdem die Axen des _Scatterplots_ beschriftet und die einzelnen _DataPoints_ erzeugt.
Wurde ein _DataPoint_ vom Benutzer ausgewählt, wird die Methode _SelectDataPoint(int)_ aufgerufen (vgl. <<ScatterplotMatrix>>).
Der _Scatterplot_ iterriert über alle seiner _DataPoints_ und hebt den durch den Index bestimmten _DataPoint_
hervor.

Ein wichtiger Teil der _Scatterplot_ Komponente ist die Methode _OnMVRWandEnter(VRSelection)_. Diese 
Methode wird immer dann aufgerufen, wenn der Wand auf den _Scatterplot_ trifft. In diesem Fall wird
der Collider des _Scatterplots_ deaktiviert und die Collider aller seiner _DataPoints_ werden aktiviert.
War zuvor ein anderer _Scatterplot_ vom Wand ausgewählt, so werden die Collider seiner _DataPoints_ wieder
deaktiviert und sein eigener Collider aktiviert, damit er das nächste Mal wieder darauf reagieren kann.
Durch dieses Vorgehen wird die maximale Anzahl an aktivierten Collidern in Unity begrenzt. Würde dies nicht
so gehandhabt werden, kann es passiert, dass Unity eine Fehlermeldung wirft, wenn zu viele _DataPoints_
erzeugt werden.

=== DataPoint
Die Komponente _DataPoint_ visuaisiert eine Zeile der CSV-Datei als Kugel in einem Scatterplot.
Auch nach dem Erzeugen eines _DataPoints_ sollte immer die _Initialize(int, float, Vector3)_ Methode
aufgerufen werden. Durch den Index erhält der _DataPoint_ seine zuordnung zu einer Zeile der CSV-Datei,
die Größe des _DataPoints_ wird durch den _float_-Wert definiert und seine Position durch den _Vector3_.
Außerdem wird bei der Initialisierung der Text des Attributsdialog gesetzt. Dieser wird angezeigt, 
wenn der Benutzer den _DataPoint_ auswählt. Über die Methode _GetData()_ können die Werte des _DataPoints_
erhalten werden. Der Rückgabewert der Methode ist ein zweidimensionales _string_-Array. Die erste Dimension
repräsentiert die drei Achsen des _DataPoints_ in der zweiten wird der Identifizierer der CSV-Spalte mit dem 
Index 0 angegeben und der entsprechende Werte des _DataPoints_ mit Index 1.

Wenn der Benutzer den _DataPoint_ auswählt, wird die Methode _VRAction(VRSelection)_ aufgerufen.
Der _DataPoint_ gibt dann seinen Index an die _ScatterplotMatrix_ über die Methode _SelectDataPoint(int)_
weiter (vgl. <<ScatterplotMatrix>>), damit alle _Scatterplots_ benachrichtigt werden können.

=== Programmablauf
Das folgende Diagramm stellt den Programmablauf beim erstmaligen Starten der Anwendung dar:

* Blub
** Blub
* blub

Blub

. Ich
.. Mag 
... Züge
. du
.. magst
... LKW
.... Tut Tut


==== Neue Subüberschrift
Blub <<referenz_auf_bereich>>

[[referenz_auf_bereich]]
.Mein Bereich
====
Übernimmt Ascii Zeug
====

[source, c#]
.Source Code
----
public void Foo(){

}
----

Und noch Ref auf Überschrift <<Neue Subüberschrift>>.

include::bib.adoc[]